[program:nginx]
command=/bin/sh -c "envsubst '${PORT} ${NGINX_PORT}' < /etc/nginx/nginx.conf.template > /etc/nginx/sites-enabled/default && exec nginx -g 'daemon off;'"
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:radar]
command=python src/main.py
directory=/app
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
